### ISSUE TITLE
jaja een eerste test van Jan 

### ISSUE THREAD

**Issue by lefebvregoderik** [lefebvregoderik/Git_Zen_repository#16]
***This ticket was escalated from Zendesk by Katrien Demaeght:***

  **Ticket:** [#18](https://informat1602745064.zendesk.com/agent/tickets/18)
  **Type:** Question
  **Priority:** Normal
  **Requester:** Katrien Demaeght
  **Organization:** Informat Sandbox
  **Assignee:** Katrien Demaeght
***

**Katrien Demaeght** 2/24/2022 10:24 am
er zijn geen problemen meer te melden van de klanten  
Informat is top  
  
toch katrien?  

Met vriendelijke groeten,  
Katrien Demaeght

---

**Katrien Demaeght** 2/24/2022 10:26 am *(private)*
Dag collega’s

Alles is volledig onder controle dankzij jullie 😊

groeten  
Katrien

---

**Katrien Demaeght** 2/24/2022 10:26 am *(private)*
Ola goed bezig Jan

Je wordt nog een echte professional samen met Goderik

---

**Katrien Demaeght** 2/24/2022 10:31 am *(private)*
jan, kan dit snel opgepikt worden  
want tis echt wel kweetnieoedringend   
  
![](https://informat1602745064.zendesk.com/attachments/token/iayjx5qZ2woPSaQgMZOR21dGU/?name=inline-1161057914.png)​
 gz#18

**Comment by jvermaut** [comment]
tis opgelost

**Comment by lefebvregoderik** [comment]
Agent comment from Katrien Demaeght in <a href='https://informat1602745064.zendesk.com/agent/tickets/18'>Zendesk ticket #18</a>:<br><br>oei ik was nog iets vergeten te vermelden
<br><p><em><small>°°°</small></em></p>

**Comment by lefebvregoderik** [comment]
Agent comment from Katrien Demaeght in <a href='https://informat1602745064.zendesk.com/agent/tickets/18'>Zendesk ticket #18</a>:<br><br>oei ik was nog iets vergeten te vermelden
<br><p><em><small>°°°</small></em></p>
