### ISSUE TITLE
o365 aanvraag

### ISSUE THREAD

**Issue by lefebvregoderik** [lefebvregoderik/Git_Zen_repository#17]
***This ticket was escalated from Zendesk by Katrien Demaeght:***

  **Ticket:** [#19](https://informat1602745064.zendesk.com/agent/tickets/19)
  **Type:** Ticket
  **Priority:** -
  **Requester:** Katrien Demaeght
  **Organization:** Informat Sandbox
  **Assignee:** Katrien Demaeght
***

**Katrien Demaeght** 2/24/2022 10:42 am *(private)*
Jan  
  
School A wil de koppeling met O365
 gz#19

gz#21

**Comment by lefebvregoderik** [comment]
't moet zijn dat het goed geprogrammeerd is

**Comment by jvermaut** [comment]
ok ik heb nu weet van aanvraag 2 en 3

**Comment by lefebvregoderik** [comment]
Agent comment from Katrien Demaeght in <a href='https://informat1602745064.zendesk.com/agent/tickets/21'>Zendesk ticket #21</a>:<br><br>Amai niet

En dat gaat hier nogal vooruit ook<br><a href='https://informat1602745064.zendesk.com/attachments/token/qkutrur3eddTn3j3PDBThUDmE' target='zd_attach'>~WRD0003.jpg</a>
<br><p><em><small>°°°</small></em></p>

**Comment by lefebvregoderik** [comment]
Agent comment from Katrien Demaeght in <a href='https://informat1602745064.zendesk.com/agent/tickets/21'>Zendesk ticket #21</a>:<br><br>Amai niet

En dat gaat hier nogal vooruit ook<br><a href='https://informat1602745064.zendesk.com/attachments/token/qkutrur3eddTn3j3PDBThUDmE' target='zd_attach'>~WRD0003.jpg</a>
<br><p><em><small>°°°</small></em></p>
